<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoftwareLearningGuide.Application\SoftwareLearningGuide.Application.csproj" />
    <ProjectReference Include="..\SoftwareLearningGuide.Application.Command\SoftwareLearningGuide.Application.Command.csproj" />
    <ProjectReference Include="..\SoftwareLearningGuide.Infraestructure.Data\SoftwareLearningGuide.Infraestructure.Data.csproj" />
  </ItemGroup>



</Project>
